In [ ]:
import pandas as pd


In [ ]:
num = input("Enter the number : ")

try:
    number=int(num)
    print("Input is an integer number. Number = ", number)
    #fact=1
    try:
        if number>0:
            fact=1
            while number >0:
                fact=fact*number
                number=number-1
            print(f"The factorial is:{fact}")
            
        elif number==0:
            print(f"factorial=1")
        else:
            print(f"negative number")
    except:
        print("wrong input")
        
except:
    print(f"Input is not an integer number.")
        

In [17]:
def fact(numx):
    try:
        number=int(numx)
        print("Input is an integer number. Number = ", number)
    #fact=1
        try:
            if number>0:
                fact=1
                while number >0:
                    fact=fact*number
                    number=number-1
                print(f"The factorial is:{fact}")

            elif number==0:
                
                fact="factorial=1"
            else:
                print(f"negative number")
                fact="undefined"
        except:
            print("wrong input")
            fact="undefined"
        
    except:
        print(f"Input is not an integer number.")
        fact="undefined"
    
    return fact


In [18]:
num = input("Enter the number : ")
answer= fact(num)
print(answer)

Enter the number : 0
Input is an integer number. Number =  0
factorial=1


In [12]:
_ = int(input())
s1 = set(map(int, input().split()))
N = int(input())

for _ in range(N):
    cmd, _ = input().split()
    s2 = set(map(int, input().split()))
    if(cmd == "intersection_update"):
        s1.intersection_update(s2)
    elif(cmd == "update"):
        s1.update(s2)
    elif(cmd == "symmetric_difference_update"):
        s1.symmetric_difference_update(s2)
    elif(cmd == "difference_update"):
        s1.difference_update(s2)

print(sum(s1))

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


In [13]:
# set mutations
_ = int(input())
set1 = set(map(int, input().split()))
N = int(input())

for _ in range(N):
    cmd, _ = input().split()
    set2 = set(map(int, input().split()))
    if (cmd == "intersection_update"):
        set1.intersection_update(set2)
    elif (cmd == "update"):
        set1.update(set2)
    elif (cmd == "symmetric_difference_update"):
        set1.symmetric_difference_update(set2)
    elif (cmd == "difference_update"):
        set1.difference_update(set2)
        
print(sum(set1))

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


In [2]:
k  = int(input())
rooms = list(map(int, input().split()))

for room in rooms:
    if rooms.count(room)==1:
        print(room)

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2 
8


In [5]:
# The Captain's Room
k  = int(input())
rooms = list(map(int, input().split()))
myset = set(rooms)
print(myset)
print(sum(myset))
print(sum(rooms))
print(((sum(myset)*k)-(sum(rooms)))//(k-1))

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
{1, 2, 3, 4, 5, 6, 8}
29
113
8


In [1]:
# Check Subset
t = int(input())

for i in range(t):
    na = int(input())
    A = set(map(int, input().split()))
    nb = int(input())
    B = set(map(int,input().split()))
    print(A.issubset(B))

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


In [5]:
# Check Strict Superset
A = set(map(int, input().split()))
n = int(input())

for i in range(n):
    B = set(map(int, input().split()))
    
print(A.issuperset(B))

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


In [6]:
a = set(map(str, input().split(' ')))
is_strict_superset = []
for i in range(int(input())):
     is_strict_superset.append(a.issuperset(set(map(str, input().split(' ')))))
print(all(is_strict_superset))

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


In [7]:
a = set(input().split())
print(all(a > set(input().split()) for _ in range(int(input()))))

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


In [12]:
# Input()
ul = input().split()
x = int(ul[0])
print(eval(input()) == int(ul[1]))

1 4
x**3 + x**2 + x + 1
True


In [14]:
# Python Evaluation
# The eval() expression is a very powerful built-in function of Python. It helps in evaluating 
# an expression. The expression can be a Python statement, or a code object.
eval(input())

print(2 + 3)
5


In [22]:
# Athlete Sort
from operator import itemgetter
nm = input().split()

n = int(nm[0])

m = int(nm[1])

arr = []
    
for _ in range(n):
    arr.append(list(map(int, input().rstrip().split())))

print(arr)

k = int(input())

print(sorted(arr, key=itemgetter(k)))

for i in sorted(arr, key=itemgetter(k)):
    print(*i)


5 3
10 2 5
7 1 0
9 9 9
1 23 12
6 5 9
[[10, 2, 5], [7, 1, 0], [9, 9, 9], [1, 23, 12], [6, 5, 9]]
1
[[7, 1, 0], [10, 2, 5], [6, 5, 9], [9, 9, 9], [1, 23, 12]]
7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


It’s safer to just unpack the sequence with the star operator (*) and let print() handle type casting:
print(*['jdoe is', 42, 'years old'])
jdoe is 42 years old

In [29]:
# Any or All
n = input()
mylist = input().split()
print(mylist[::-1]) # print the list in reverse order
print(all([int(i)>0 for i in mylist]) and any([j==j[::-1] for j in mylist]))      

5
12 9 61 5 14 
['14', '5', '61', '9', '12']
True


In [54]:
#ginortS (sorting the string as per the recommendation: lowercase->uppercase->odd digits->even digits)
l,u,o,e=[],[],[],[]

for i in sorted(input()):
    if i.isalpha():
        if i.isupper():
            x = u
        else:
            x = l
    else:
        if int(float(i))%2==0:
            x = e
        else: 
            x = o
    x.append(i)
print("".join(l+u+o+e))        

Sorting1234
ginortS1324


In [37]:
#ginortS (sorting)
myList = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1357902468"
print(*sorted(input(), key = myList.index), sep ="")

<built-in method index of str object at 0x000001F786A7A650>
Sorting1234
ginortS1324


In [41]:
sorted(input())

1256394


['1', '2', '3', '4', '5', '6', '9']

In [97]:
# itertools.combinations()
from itertools import combinations
sk=input().split()
k=int(sk[1])
print(k)
for i in range(1,k+1):
    sor=sorted(sk[0])
    print(list(combinations(sor,i)))
    for j in combinations(sor, i):
        print(j)
        print(''.join(j))        

hack 2
2
[('a',), ('c',), ('h',), ('k',)]
('a',)
a
('c',)
c
('h',)
h
('k',)
k
[('a', 'c'), ('a', 'h'), ('a', 'k'), ('c', 'h'), ('c', 'k'), ('h', 'k')]
('a', 'c')
ac
('a', 'h')
ah
('a', 'k')
ak
('c', 'h')
ch
('c', 'k')
ck
('h', 'k')
hk


In [101]:
j=('a',)
print(''.join(j)) 

a


In [ ]:
from itertools import combinations

s , n  = raw_input().split()

for i in range(1, int(n)+1):
    for j in combinations(sorted(s), i):
        print ''.join(j)

In [110]:
# itertools.combinations_with_replacement()
from itertools import combinations_with_replacement
sk=input().split()
k=int(sk[1])
print(k)
sor=sorted(sk[0])
mylist=list(combinations_with_replacement(sor,k))
print(mylist)
for i in mylist:
    print(''.join(i))   

hack 2
2
[('a', 'a'), ('a', 'c'), ('a', 'h'), ('a', 'k'), ('c', 'c'), ('c', 'h'), ('c', 'k'), ('h', 'h'), ('h', 'k'), ('k', 'k')]
aa
ac
ah
ak
cc
ch
ck
hh
hk
kk


In [14]:
# Compress the String!

from itertools import groupby
print(*[(len(list(c)), int(k)) for k, c in groupby(input())])

111222111333
(3, 1) (3, 2) (3, 1) (3, 3)


Basically I'm unpacking the list comprehension and printing each element of it.

The list is built of elements of (len(list(c)), int(k)). len(list(c)) is simply the number of occurences of a character c returned by the groupby function. k is just the key value, the character itself.

In [ ]:
#Iterables and Iterators
from itertools import combinations

_,s,n = input(),input().split(),int(input())
t = list(combinations(s,n))
f = [i for i in t if 'a' in i]
print(len(f)/len(t))

In [45]:
#Iterables and Iterators
from itertools import combinations

N = int(input())
L = input().split()
K = int(input())
C = list(combinations(L, K))
F = filter(lambda c: 'a' in c, C)

print("{0:.3}".format(len(list(F))/len(C)))

4
a a c d
2
0.833


In [50]:
# Iterables and Iterators
from itertools import combinations

n = int(input())
l = input().split()
k = int(input())
com = list(combinations(l,k))
filtered = filter(lambda c: 'a' in c, com)

print("{0:.3}".format(len(list(filtered))/len(com)))

4
a a c d
2
0.833


In [18]:
k,m = input().split()
num = 1
maxsum = 0
for i in range(int(k)):
    mylist = list(map(int,input().split()))
    mylist.sort(reverse=True)
    print(mylist[0])
    for j in len(mylist):
        maxsum = maxsum + mylist[0]*mylist[0]
        result = maxsum % m
    if 
print(maxsum)

3 1000
2 5 4
5
3 7 8 9 
9
5 5 7 8 9 10 
10
206


In [ ]:
3 1000
2 5 4
3 7 8 9 
5 5 7 8 9 10 

In [ ]:
from itertools import product

K,M = map(int,input().split())
N = (list(map(int, input().split()))[1:] for _ in range(K))

results = map(lambda x: sum(i**2 for i in x)%M, product(*N))

print(max(results))


In [20]:
# Maximize It!
from itertools import product

k,m = map(int,input().split())
n = (list(map(int, input().split()))[1:] for _ in range(k))

results = map(lambda x: sum(i**2 for i in x)%m, product(*n))

print(max(results))


3 1000
<generator object <genexpr> at 0x0000018A0374CB48>
2 5 4
3 7 8 9 
5 5 7 8 9 10 
206


In [1]:
#Validating UID

import re

for _ in range(int(input())):
    u = ''.join(sorted(input()))
    try:
        assert re.search(r'[A-Z]{2}', u)
        assert re.search(r'\d\d\d', u)
        assert not re.search(r'[^a-zA-Z0-9]', u)
        assert not re.search(r'(.)\1', u)
        assert len(u) == 10
    except:
        print('Invalid')
    else:
        print('Valid')


2
B1CD102354
Invalid
B1CDEF2354
Valid


In [6]:
# Validating Credit Card Numbers
import re

TESTER = re.compile(
    r"^"
    r"(?!.*(\d)(-?\1){3})"
    r"[456]"
    r"\d{3}"
    r"(?:-?\d{4}){3}"
    r"$")

for _ in range(int(input().strip())):
    print("Valid" if TESTER.search(input().strip()) else "Invalid")


6
4123456789123456
Valid
5123-4567-8912-3456
Valid

Invalid
61234-567-8912-3456
Invalid
4123356789123456
Valid
5133-3367-8912-3456
Invalid


In [7]:
# Validating Credit Card Numbers
import re

def check(card):
    if not re.search("^[456]\d{3}(-?\d{4}){3}$",card) or re.search(r"(\d)\1{3}", re.sub("-", "",card)):
        return False
    return True

for i in range(int(input())):
    print("Valid" if check(input()) else "Invalid")

4
5123 - 3567 - 8912 - 3456
Invalid
4123456789123456
Valid
5123-4567-8912-3456
Valid
5133-3367-8912-3456
Invalid


In [11]:
from itertools import product
a = map(int,input().split())
b = map(int,input().split())
print(*list(product(a,b)))

1 2
3 4
(1, 3) (1, 4) (2, 3) (2, 4)


In [17]:
from itertools import permutations
s,k = input().split()
print(list(permutations(sorted(s),int(k))))
print(*list(permutations(sorted(s),int(k))))
print([''.join(i) for i in permutations(sorted(s),int(k))],sep='\n')
print(*[''.join(i) for i in permutations(sorted(s),int(k))])
print(*[''.join(i) for i in permutations(sorted(s),int(k))],sep='\n')

HACK 2
[('A', 'C'), ('A', 'H'), ('A', 'K'), ('C', 'A'), ('C', 'H'), ('C', 'K'), ('H', 'A'), ('H', 'C'), ('H', 'K'), ('K', 'A'), ('K', 'C'), ('K', 'H')]
('A', 'C') ('A', 'H') ('A', 'K') ('C', 'A') ('C', 'H') ('C', 'K') ('H', 'A') ('H', 'C') ('H', 'K') ('K', 'A') ('K', 'C') ('K', 'H')
['AC', 'AH', 'AK', 'CA', 'CH', 'CK', 'HA', 'HC', 'HK', 'KA', 'KC', 'KH']
AC AH AK CA CH CK HA HC HK KA KC KH
AC
AH
AK
CA
CH
CK
HA
HC
HK
KA
KC
KH


In [5]:
import numpy
n,m,p=map(int,input().split())

arr1=numpy.array([input().split() for _ in range(n)],int)   
print(arr1)
arr2=numpy.array([input().split() for _ in range(m)],int)
print(arr2)

print(numpy.concatenate((arr1, arr2), axis = 0)) 

4 3 2
1 2
1 2
1 2
1 2
[[1 2]
 [1 2]
 [1 2]
 [1 2]]
3 4
3 4
3 4
[[3 4]
 [3 4]
 [3 4]]
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [4]:
#Zeros and Ones
import numpy
a,b,c=map(int,input().split())

print(numpy.zeros((a,a), dtype = numpy.int))
print(numpy.zeros((b,b), dtype = numpy.int))
print(numpy.zeros((c,c), dtype = numpy.int))

print(numpy.ones((a,a), dtype = numpy.int))
print(numpy.ones((b,b), dtype = numpy.int))
print(numpy.ones((c,c), dtype = numpy.int))

3 3 3
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
#Zeros and Ones
import numpy
nums = tuple(map(int,input().split()))
print(numpy.zeros(nums, dtype = numpy.int))
print(numpy.ones(nums, dtype = numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [19]:
import numpy
n,m = map(int,input().split())
print(numpy.eye(n, m, k = 0))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
#Set .add()
n = int(input())
stamps = set()
for _ in range(n):
    stamps.add(input().strip())
        
print(len(stamps))


7
UK
China
USA
France
New Zealand
UK
France 
5


In [16]:
#Set .discard(), .remove() & .pop()

n = int(input())
s = set([int(x) for x in input().strip().split()])

for _ in range(int(input())):
    com = list(input().strip().split())
               
    if com[0] == "pop":
        s.pop()
    elif com[0] == "discard":
        s.discard(int(com[1]))
    else:
        s.remove(int(com[1]))
        
    print(s)
              
print(sum(s))

9
1 2 3 4 5 6 7 8 9
10
pop
{2, 3, 4, 5, 6, 7, 8, 9}
remove 9
{2, 3, 4, 5, 6, 7, 8}
discard 9
{2, 3, 4, 5, 6, 7, 8}
discard 8
{2, 3, 4, 5, 6, 7}
remove 7
{2, 3, 4, 5, 6}
pop 
{3, 4, 5, 6}
discard 6
{3, 4, 5}
remove 5
{3, 4}
pop 
{4}
discard 5
{4}
4


In [4]:
n=int(input())
eng=set(input().split())
b=int(input())
fre=set(input().split())
print(eng|fre)
print(len(eng|fre))

2
1 2
3 
1 3 4
{'2', '4', '1', '3'}
4


In [5]:
n=int(input())
eng=set(input().split())
b=int(input())
fre=set(input().split())
print(eng & fre)
print(len(eng & fre))

2
1 2
3 
1 3 4
{'1'}
1


In [6]:
n=int(input())
eng=set(input().split())
b=int(input())
fre=set(input().split())
print(eng - fre)
print(len(eng - fre))

2
1 2
3
1 3 4
{'2'}
1


In [8]:
n=int(input())
eng=set(input().split())
b=int(input())
fre=set(input().split())
print(eng^fre)
print(len(eng^fre))

2 
1 2
3
1 3 4
{'2', '4', '3'}
3


In [1]:
n=int(input())
eng=set(input().split())
b=int(input())
fre=set(input().split())
# print(eng|fre)
print(len(eng|fre))


2
1 2
3
1 2 3
3


In [3]:
a=int(input())
b=int(input())
m=int(input())
print(pow(a,b))
print(pow(a,b,m))

3
4
5
81
1


In [4]:
a=int(input())
b=int(input())
c=int(input())
d=int(input())
s1=pow(a,b)
print(s1)
s2=pow(c,d)
print(s2)
print(s1+s2)

9
29
7
27
4710128697246244834921603689
65712362363534280139543
4710194409608608369201743232


In [9]:
for i in range(1,int(input())): #More than 2 lines will result in 0 score. Do not leave a blank line also
    print((10**(i)//9)*i)
    

5
1
22
333
4444


In [11]:
n,m = input().split()

1 2


In [14]:
import math
import os
import random
import re
import sys


first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)    
    
encoded_string = "".join([matrix[j][i] for i in range (m) for j in range (n)])
pat = r'(?<=[a-zA-Z0-9])[^a-zA-Z0-9]+(?=[a-zA-Z0-9])'
print(re.sub(pat,' ',encoded_string))


7 3
Tsi
h%x
i #
sM 
$a 
#t%
ir!
This is Matrix#  %!


In [18]:
n = int(input())
s = set([int(x) for x in input().strip().split()])
avg= sum(s)/len(s)
print(avg)

10
161 182 161 154 176 170 167 171 170 174
169.375


In [19]:
def average(array):
    # your code goes here    
    return sum(set(array))/len(set(array))
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


In [1]:
a = int(input())
b = int(input())
print(a//b)
print(a%b)
print(divmod(a,b))

177
10
17
7
(17, 7)


In [16]:
import numpy as np
print(np.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
import numpy
n,m = map(int,input().split())
array1=numpy.array([input().strip().split() for _ in range(n)],int)
    
print(array1.transpose())
print(array1.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [28]:
import numpy
n,m = map(int,input().split())
a = numpy.array([input().strip().split() for _ in range(n)],int)
b =numpy.array([input().strip().split() for _ in range(n)],int)
print(numpy.add(a, b))
print(numpy.subtract(a, b))
print(numpy.multiply(a, b))
print(a//b)
print(numpy.mod(a, b))
print(numpy.power(a, b))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [33]:
numpy.set_printoptions(sign=' ')

my_array = numpy.array(input().strip().split(),float)
print(numpy.floor(my_array))
print(numpy.ceil(my_array))
print(numpy.rint(my_array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [35]:
import numpy
n,m = map(int,input().split())
array1 = numpy.array([input().strip().split() for _ in range(n)],int)
array2 = numpy.sum(array1, axis = 0)
print(numpy.prod(array2))

2 2
1 2
3 4
24


In [1]:
# Min and Max
import numpy
n,m = map(int,input().split())
array1 = numpy.array([input().strip().split() for _ in range(n)],int)
array2 = numpy.min(array1, axis = 1)
print(numpy.max(array2))

4 2
2 5
3 7
1 3
4 0
3


In [3]:
# Mean, Var, and Std
import numpy
numpy.set_printoptions(legacy='1.13')
n,m = map(int,input().split())
array1 = numpy.array([input().strip().split() for _ in range(n)],int)
print(numpy.mean(array1, axis = 1))
print(numpy.var(array1, axis = 0))
print(numpy.std(array1))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [2]:
 # Dot and Cross
import numpy
n = int(input())
A = numpy.array([input().strip().split() for _ in range(n)],int)
B = numpy.array([input().strip().split() for _ in range(n)],int)
print(numpy.dot(A, B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [9]:
#Inner and Outer
import numpy
A = numpy.array(input().strip().split(),int)
B = numpy.array(input().strip().split(),int)
print(numpy.inner(A,B))
print(numpy.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]
